[general]
import = ["themes/themes-alacritty/gotham.toml"]

[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
thickness = 0.25
unfocused_hollow = false

[cursor.style]
blinking = "Never"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 8.0

[font.bold]
family = "Hermit"
style = "Bold"

[font.bold_italic]
family = "Hermit"
style = "BoldItalic"

[font.italic]
family = "Hermit"
style = "Italic"

[font.normal]
family = "Hermit"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window.padding]
x = 0
y = 0
